import type { StatusKey } from '../data/statuses'
import type { SectionKey } from '../data/sections'

export interface Item {
  id: string
  name: string
  status: StatusKey
  section: SectionKey
  notes: string[]
  invenInfo: string
}

export const defaultItems: Item[] = [
  // #region 1 Beverage
  {
    id: '1001',
    name: 'Milk',
    status: 'undefined',
    section: 'Beverage',
    notes: [],
    invenInfo: '6 white bags',
  },

  {
    id: '1002',
    name: 'Oat Milk',
    status: 'undefined',
    section: 'Beverage',
    notes: [],
    invenInfo: '5 oat boxes',
  },

  {
    id: '1003',
    name: 'Sparkling',
    status: 'undefined',
    section: 'Beverage',
    notes: [],
    invenInfo: '6 bottles',
  },

  {
    id: '1004',
    name: 'Coffee Bean_Brazil',
    status: 'undefined',
    section: 'Beverage',
    notes: [],
    invenInfo: '1 silver bag',
  },
  
  {
    id: '10041',
    name: 'Coffee Bean_Colombia',
    status: 'undefined',
    section: 'Beverage',
    notes: [],
    invenInfo: '1 silver bag',
  },

  {
    id: '1005',
    name: 'Retail Coffee Bean',
    status: 'undefined',
    section: 'Beverage',
    notes: [],
    invenInfo: '1 black bag',
  },

  {
    id: '1006',
    name: 'Simple Syrup',
    status: 'undefined',
    section: 'Beverage',
    notes: [],
    invenInfo: 'tall container and 2 squeez bottles',
  },

  {
    id: '1007',
    name: 'Vanilla Syrup',
    status: 'undefined',
    section: 'Beverage',
    notes: [],
    invenInfo: '<em class="text-green-800 font-bold">Green</em> box and 2 squeez bottles',
  },

  {
    id: '1008',
    name: 'Yuzu Syrup',
    status: 'undefined',
    section: 'Beverage',
    notes: [],
    invenInfo: '<em class="text-red-800 font-bold">Red</em> box and 2 squeez bottles',
  },

  {
    id: '1009',
    name: 'Lemon Syrup',
    status: 'undefined',
    section: 'Beverage',
    notes: [],
    invenInfo: '<em class="text-red-800 font-bold">Red</em> box and 2 squeez bottles',
  },

  {
    id: '1010',
    name: 'Caramel',
    status: 'undefined',
    section: 'Beverage',
    notes: [],
    invenInfo: '<em class="text-red-800 font-bold">Red</em> box and 2 squeez bottles',
  },

  {
    id: '1011',
    name: 'Nutella',
    status: 'undefined',
    section: 'Beverage',
    notes: [],
    invenInfo: '1 large squeez bottle',
  },

  {
    id: '1012',
    name: 'Strawberry Syrup',
    status: 'undefined',
    section: 'Beverage',
    notes: [],
    invenInfo: '<em class="text-red-800 font-bold">Red</em> box and 2 squeez bottles',
  },

  {
    id: '1013',
    name: 'Matcha',
    status: 'undefined',
    section: 'Beverage',
    notes: [],
    invenInfo: '3 short containers',
  },

  {
    id: '1014',
    name: 'Hojicha',
    status: 'undefined',
    section: 'Beverage',
    notes: [],
    invenInfo: '2 tall containers',
  },

  {
    id: '1015',
    name: 'Coco Powder',
    status: 'undefined',
    section: 'Beverage',
    notes: [],
    invenInfo: '1 short container',
  },

  {
    id: '1016',
    name: 'Cinnamon Powder',
    status: 'undefined',
    section: 'Beverage',
    notes: [],
    invenInfo: '1 short container',
  },

  {
    id: '1017',
    name: 'Korean Chai',
    status: 'undefined',
    section: 'Beverage',
    notes: [],
    invenInfo: '<em class="text-red-800 font-bold">Red</em> box and 2 kettles',
  },

    {
    id: '10171',
    name: 'Korean Chai-oat',
    status: 'undefined',
    section: 'Beverage',
    notes: [],
    invenInfo: '2 kettles',
  },

  //#endregion

  // #region 2 Craffle
  {
    id: '2001',
    name: 'Whipped Cream',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '2 6pan',
  },
  {
    id: '2002',
    name: 'Cheese',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '2 6pan',
  },
  {
    id: '2003',
    name: 'Egg Salad',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '2 6pan',
  },
  {
    id: '2004',
    name: 'Corn',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '2 6pan',
  },
  {
    id: '2005',
    name: 'Ham',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '3 bags',
  },
  {
    id: '2006',
    name: 'Turkey',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '3 bags',
  },
  {
    id: '2007',
    name: 'Pecorino Cheese',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '1 short container',
  },
  {
    id: '2008',
    name: 'Mixed Spring',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '2 3pans',
  },
  {
    id: '2009',
    name: 'Argula',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '2 3pans',
  },
  {
    id: '2010',
    name: 'Strawberry',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '1 6pan',
  },
  {
    id: '2011',
    name: 'Banana',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '5 bananas',
  },
  {
    id: '2012',
    name: 'Biscoff Cookie',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '1 tall container',
  },
  {
    id: '2013',
    name: 'Biscoff Crumb',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '1 tall container',
  },
  {
    id: '2014',
    name: 'Oreo',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '1 tall container',
  },
  {
    id: '2015',
    name: 'Oreo Crumb',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '1 tall container',
  },
  {
    id: '2016',
    name: 'Cinn & Sugar',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '1 half-pan',
  },
  {
    id: '2017',
    name: 'Crispy Onion',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '1 steel mini-pan and 1 short container',
  },
  {
    id: '2018',
    name: 'Olive Powder',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '1 steel mini-pan and 1 short container',
  },
  {
    id: '2019',
    name: 'Sugar',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '1 steel mini-pan',
  },
  {
    id: '2020',
    name: 'Yeast Powder',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '1 steel mini-pan and 1 short container',
  },
  {
    id: '2021',
    name: 'Salt',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '1 steel mini-pan and 1 short container',
  },
  {
    id: '2022',
    name: 'Sesame Seed',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '1 steel mini-pan and 1 short container',
  },
  {
    id: '2023',
    name: 'Choco Curl',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '1 steel mini-pan and 1 short container',
  },
  {
    id: '2024',
    name: 'Choco Pearl',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '1 steel mini-pan and 1 short container',
  },
  {
    id: '2025',
    name: 'Black Pepper',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '1 bottle',
  },
  {
    id: '2026',
    name: 'Raspberry Powder',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '1 short container',
  },
  {
    id: '2027',
    name: 'Pumpkin Seed',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '1 short container',
  },
  {
    id: '2028',
    name: 'Soup',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '1 <em class="text-red-800 font-bold">Red</em> box',
  },
  {
    id: '2029',
    name: 'Bulgogi',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '2 6pans',
  },
  {
    id: '2031',
    name: 'Korean Chicken',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '2 6pans',
  },
  {
    id: '2032',
    name: 'Pickled Shallots',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '2 short container',
  },
  {
    id: '2033',
    name: 'Rosemary',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '<em class="text-red-800 font-bold">Red</em> box and 2 squeez bottles',
  },
  {
    id: '2034',
    name: 'Yuzu Dressing',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '1 squeez bottle',
  },
  {
    id: '2035',
    name: 'KFC Sauce',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '<em class="text-red-800 font-bold">Red</em> box and 2 squeez bottles',
  },
  {
    id: '2036',
    name: 'Caramel',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '<em class="text-red-800 font-bold">Red</em> box and 2 squeez bottles',
  },
  {
    id: '2037',
    name: 'Nutella',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '1 bag',
  },
  {
    id: '2038',
    name: 'Choco Syrup',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '<em class="text-red-800 font-bold">Red</em> box and 2 squeez bottles',
  },
  {
    id: '2039',
    name: 'Milk Syrup',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '2 squeez bottles',
  },
  {
    id: '2040',
    name: 'Sesame Syrup',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '1 tall container and 2 squeez bottles',
  },
  {
    id: '2041',
    name: 'Mayo',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '3 red squeez bottles',
  },
  {
    id: '2042',
    name: 'Strawberry Jam',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '<em class="text-red-800 font-bold">Red</em> box and 2 squeez bottles',
  },
  {
    id: '2043',
    name: 'Bulgogi Sauce',
    status: 'undefined',
    section: 'craffle',
    notes: [],
    invenInfo: '<em class="text-red-800 font-bold">Red</em> box and 2 squeez bottles',
  },

  // #endregion

  // #region 3 Wholesale
  {
    id: '3001',
    name: 'Dubai Chewy Cookie',
    status: 'undefined',
    section: 'wholesale',
    notes: [],
    invenInfo: '6 to-go in front refirgerator, 10 in 3 pan',
  },
  {
    id: '3002',
    name: 'Butter Ttoek',
    status: 'undefined',
    section: 'wholesale',
    notes: [],
    invenInfo: 'Double-check per day',
  },

  // #endregion

  // #region 4 Catering
  {
    id: '4001',
    name: 'Box',
    status: 'undefined',
    section: 'catering',
    notes: [],
    invenInfo: 'N/A',
  },
  {
    id: '4002',
    name: 'Sticker',
    status: 'undefined',
    section: 'catering',
    notes: [],
    invenInfo: 'N/A',
  },
  // #endregion

  // #region 5 special
  {
    id: '5002',
    name: 'Special Lid',
    status: 'undefined',
    section: 'special',
    notes: [],
    invenInfo: '1 column',
  },

  {
    id: '5004',
    name: 'Lime Syrup',
    status: 'undefined',
    section: 'special',
    notes: [],
    invenInfo: '<em class="text-green-800 font-bold">Green</em> box and 1 squeez bottle',
  },
  {
    id: '5010',
    name: 'Lime Slice',
    status: 'undefined',
    section: 'special',
    notes: [],
    invenInfo: '1 9pan',
  },
  {
    id: '5011',
    name: 'Mint',
    status: 'undefined',
    section: 'special',
    notes: [],
    invenInfo: '1 <em class="text-red-800 font-bold">Red</em> box',
  },
  {
    id: '5014',
    name: 'Lime form',
    status: 'undefined',
    section: 'special',
    notes: [],
    invenInfo: '1 steel bottle',
  },

  // #endregion 

  // #region 6 disposable 
  {
    id: '6001',
    name: '10oz Hot Cup',
    status: 'undefined',
    section: 'disposable',
    notes: [],
    invenInfo: '1 column and 1 backup',
  },
  {
    id: '6002',
    name: '12oz Hot Cup',
    status: 'undefined',
    section: 'disposable',
    notes: [],
    invenInfo: '1 column and 1 backup',
  },
  {
    id: '6003',
    name: '16oz Cold Cup',
    status: 'undefined',
    section: 'disposable',
    notes: [],
    invenInfo: '2 columns and 2 backups',
  },
  {
    id: '6004',
    name: 'Hot Lid',
    status: 'undefined',
    section: 'disposable',
    notes: [],
    invenInfo: '1 column and 1 backup',
  },
  {
    id: '6005',
    name: 'Cold Lid',
    status: 'undefined',
    section: 'disposable',
    notes: [],
    invenInfo: '2 columns and 2 backups',
  },
  {
    id: '6006',
    name: 'Straw',
    status: 'undefined',
    section: 'disposable',
    notes: [],
    invenInfo: '1 9 pan and 1 paper box',
  },
  {
    id: '6007',
    name: 'Napkin',
    status: 'undefined',
    section: 'disposable',
    notes: [],
    invenInfo: '1 bag for backup',
  },
  {
    id: '6008',
    name: 'Fork & Knife',
    status: 'undefined',
    section: 'disposable',
    notes: [],
    invenInfo: '1 9 pan and 1 box',
  },
  {
    id: '6009',
    name: 'Spoon',
    status: 'undefined',
    section: 'disposable',
    notes: [],
    invenInfo: '1 9 pan and 1 box',
  },
  {
    id: '6010',
    name: 'Sugar Bag',
    status: 'undefined',
    section: 'disposable',
    notes: [],
    invenInfo: '1 small bowl and 1 box',
  },
  {
    id: '6011',
    name: 'Splenda',
    status: 'undefined',
    section: 'disposable',
    notes: [],
    invenInfo: '1 small bowl and 1 box',
  },
  {
    id: '6012',
    name: 'Sleeve',
    status: 'undefined',
    section: 'disposable',
    notes: [],
    invenInfo: '1 column',
  },
  {
    id: '6013',
    name: 'Toliet Paper',
    status: 'undefined',
    section: 'disposable',
    notes: [],
    invenInfo: '2 rolls',
  },
  {
    id: '6014',
    name: 'Toliet Hand Paper',
    status: 'undefined',
    section: 'disposable',
    notes: [],
    invenInfo: '1 roll',
  },
  {
    id: '6015',
    name: 'Starrer',
    status: 'undefined',
    section: 'disposable',
    notes: [],
    invenInfo: '1 9pan',
  },
  // #endregion

  // #region 7 Bingsu
  {
    id: '7001',
    name: 'Melon',
    status: 'undefined',
    section: 'bingsu',
    notes: [],
    invenInfo: '3 melons',
  },
  {
    id: '7002',
    name: 'Ice in Frige',
    status: 'undefined',
    section: 'bingsu',
    notes: [],
    invenInfo: '2 <em class="text-red-800 font-bold">Red</em> boxes',
  },
  {
    id: '7003',
    name: 'Ice cream',
    status: 'undefined',
    section: 'bingsu',
    notes: [],
    invenInfo: '1 tank',
  },
  {
    id: '7004',
    name: 'Bingsu Milk',
    status: 'undefined',
    section: 'bingsu',
    notes: [],
    invenInfo: '1 squeeze bottle',
  },
  {
    id: '7005',
    name: 'Melon Syrup',
    status: 'undefined',
    section: 'bingsu',
    notes: [],
    invenInfo: '1 squeeze bottle',
  },
  {
    id: '7006',
    name: 'Strawberry Jam',
    status: 'undefined',
    section: 'bingsu',
    notes: [],
    invenInfo: '1 squeeze bottle',
  },
  {
    id: '7007',
    name: 'Mango Syrup',
    status: 'undefined',
    section: 'bingsu',
    notes: [],
    invenInfo: '1 squeeze bottle',
  },
  {
    id: '7008',
    name: 'Milk Syrup',
    status: 'undefined',
    section: 'bingsu',
    notes: [],
    invenInfo: '1 squeeze bottle',
  },
  {
    id: '7009',
    name: 'Cereal',
    status: 'undefined',
    section: 'bingsu',
    notes: [],
    invenInfo: '1 <em class="text-green-800 font-bold">Green</em> box',
  },
  {
    id: '7010',
    name: 'Mint',
    status: 'undefined',
    section: 'bingsu',
    notes: [],
    invenInfo: '1 <em class="text-red-800 font-bold">Red</em> box',
  },
  // #endregion

]